# Form implementation generated from reading ui file 'bodegas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Bodega(object):
    def setupUi(self, Bodega):
        Bodega.setObjectName("Bodega")
        Bodega.resize(638, 383)
        Bodega.setStyleSheet("background-color: rgb(100, 148, 73);")
        self.label = QtWidgets.QLabel(parent=Bodega)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.txt_nombre_bodega = QtWidgets.QLineEdit(parent=Bodega)
        self.txt_nombre_bodega.setGeometry(QtCore.QRect(110, 10, 191, 20))
        self.txt_nombre_bodega.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_nombre_bodega.setObjectName("txt_nombre_bodega")
        self.btn_crear_bodega = QtWidgets.QPushButton(parent=Bodega)
        self.btn_crear_bodega.setGeometry(QtCore.QRect(20, 90, 75, 23))
        self.btn_crear_bodega.setObjectName("btn_crear_bodega")
        self.tbl_bodegas_cr = QtWidgets.QTableWidget(parent=Bodega)
        self.tbl_bodegas_cr.setGeometry(QtCore.QRect(20, 140, 571, 191))
        self.tbl_bodegas_cr.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tbl_bodegas_cr.setObjectName("tbl_bodegas_cr")
        self.tbl_bodegas_cr.setColumnCount(4)
        self.tbl_bodegas_cr.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_bodegas_cr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_bodegas_cr.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_bodegas_cr.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_bodegas_cr.setHorizontalHeaderItem(3, item)
        self.btn_eliminar_bodega = QtWidgets.QPushButton(parent=Bodega)
        self.btn_eliminar_bodega.setGeometry(QtCore.QRect(110, 90, 75, 23))
        self.btn_eliminar_bodega.setObjectName("btn_eliminar_bodega")
        self.btn_actualizar = QtWidgets.QPushButton(parent=Bodega)
        self.btn_actualizar.setGeometry(QtCore.QRect(200, 90, 75, 23))
        self.btn_actualizar.setObjectName("btn_actualizar")

        self.retranslateUi(Bodega)
        QtCore.QMetaObject.connectSlotsByName(Bodega)

    def retranslateUi(self, Bodega):
        _translate = QtCore.QCoreApplication.translate
        Bodega.setWindowTitle(_translate("Bodega", "Form"))
        self.label.setText(_translate("Bodega", "Nombre Bodega"))
        self.btn_crear_bodega.setText(_translate("Bodega", "Crear"))
        item = self.tbl_bodegas_cr.horizontalHeaderItem(0)
        item.setText(_translate("Bodega", "Bodega"))
        item = self.tbl_bodegas_cr.horizontalHeaderItem(1)
        item.setText(_translate("Bodega", "Articulo"))
        item = self.tbl_bodegas_cr.horizontalHeaderItem(2)
        item.setText(_translate("Bodega", "Cantidad"))
        item = self.tbl_bodegas_cr.horizontalHeaderItem(3)
        item.setText(_translate("Bodega", "Codigo"))
        self.btn_eliminar_bodega.setText(_translate("Bodega", "Eliminar"))
        self.btn_actualizar.setText(_translate("Bodega", "Actualizar"))
