# Form implementation generated from reading ui file 'registrostxt.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registros(object):
    def setupUi(self, Registros):
        Registros.setObjectName("Registros")
        Registros.resize(400, 300)
        Registros.setStyleSheet("background-color: rgb(60, 120, 89);")
        self.lst_registro_ingresos = QtWidgets.QListView(parent=Registros)
        self.lst_registro_ingresos.setGeometry(QtCore.QRect(20, 210, 131, 81))
        self.lst_registro_ingresos.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.lst_registro_ingresos.setObjectName("lst_registro_ingresos")
        self.label = QtWidgets.QLabel(parent=Registros)
        self.label.setGeometry(QtCore.QRect(130, 30, 151, 16))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 170, 127);")
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Registros)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 70, 351, 111))
        self.plainTextEdit.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.btn_ver_registro = QtWidgets.QPushButton(parent=Registros)
        self.btn_ver_registro.setGeometry(QtCore.QRect(290, 210, 75, 23))
        self.btn_ver_registro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_ver_registro.setObjectName("btn_ver_registro")

        self.retranslateUi(Registros)
        QtCore.QMetaObject.connectSlotsByName(Registros)

    def retranslateUi(self, Registros):
        _translate = QtCore.QCoreApplication.translate
        Registros.setWindowTitle(_translate("Registros", "Dialog"))
        self.label.setText(_translate("Registros", "     REGISTRO DE INGRESOS"))
        self.btn_ver_registro.setText(_translate("Registros", "VER"))
