# Form implementation generated from reading ui file 'Ui_registro_inventario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_V_Registro_Inventario(object):
    def setupUi(self, V_Registro_Inventario):
        V_Registro_Inventario.setObjectName("V_Registro_Inventario")
        V_Registro_Inventario.resize(706, 423)
        self.tabla_inventario = QtWidgets.QTableWidget(parent=V_Registro_Inventario)
        self.tabla_inventario.setGeometry(QtCore.QRect(40, 90, 621, 281))
        self.tabla_inventario.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tabla_inventario.setObjectName("tabla_inventario")
        self.tabla_inventario.setColumnCount(6)
        self.tabla_inventario.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(5, item)
        self.btn_edita_linea = QtWidgets.QPushButton(parent=V_Registro_Inventario)
        self.btn_edita_linea.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.btn_edita_linea.setObjectName("btn_edita_linea")
        self.btn_eliminar_linea = QtWidgets.QPushButton(parent=V_Registro_Inventario)
        self.btn_eliminar_linea.setGeometry(QtCore.QRect(140, 10, 75, 23))
        self.btn_eliminar_linea.setObjectName("btn_eliminar_linea")
        self.btn_imprimirir_inventario = QtWidgets.QPushButton(parent=V_Registro_Inventario)
        self.btn_imprimirir_inventario.setGeometry(QtCore.QRect(260, 10, 75, 23))
        self.btn_imprimirir_inventario.setObjectName("btn_imprimirir_inventario")

        self.retranslateUi(V_Registro_Inventario)
        QtCore.QMetaObject.connectSlotsByName(V_Registro_Inventario)

    def retranslateUi(self, V_Registro_Inventario):
        _translate = QtCore.QCoreApplication.translate
        V_Registro_Inventario.setWindowTitle(_translate("V_Registro_Inventario", "Form"))
        item = self.tabla_inventario.horizontalHeaderItem(0)
        item.setText(_translate("V_Registro_Inventario", "Nombre"))
        item = self.tabla_inventario.horizontalHeaderItem(1)
        item.setText(_translate("V_Registro_Inventario", "Codigo"))
        item = self.tabla_inventario.horizontalHeaderItem(2)
        item.setText(_translate("V_Registro_Inventario", "Cantidad"))
        item = self.tabla_inventario.horizontalHeaderItem(3)
        item.setText(_translate("V_Registro_Inventario", "Costo"))
        item = self.tabla_inventario.horizontalHeaderItem(4)
        item.setText(_translate("V_Registro_Inventario", "Fecha"))
        item = self.tabla_inventario.horizontalHeaderItem(5)
        item.setText(_translate("V_Registro_Inventario", "Bodega"))
        self.btn_edita_linea.setText(_translate("V_Registro_Inventario", "Editar"))
        self.btn_eliminar_linea.setText(_translate("V_Registro_Inventario", "Eliminar"))
        self.btn_imprimirir_inventario.setText(_translate("V_Registro_Inventario", "Imprimir"))
