# Form implementation generated from reading ui file 'Ui_crear_bodega.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registro_bodega(object):
    def setupUi(self, Registro_bodega):
        Registro_bodega.setObjectName("Registro_bodega")
        Registro_bodega.resize(414, 308)
        self.btn_crear_bodega = QtWidgets.QPushButton(parent=Registro_bodega)
        self.btn_crear_bodega.setGeometry(QtCore.QRect(10, 220, 75, 23))
        self.btn_crear_bodega.setObjectName("btn_crear_bodega")
        self.label = QtWidgets.QLabel(parent=Registro_bodega)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Registro_bodega)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 111, 16))
        self.label_2.setObjectName("label_2")
        self.listView_bodegas = QtWidgets.QListView(parent=Registro_bodega)
        self.listView_bodegas.setGeometry(QtCore.QRect(140, 100, 256, 192))
        self.listView_bodegas.setObjectName("listView_bodegas")
        self.btn_actualizar_bodega = QtWidgets.QPushButton(parent=Registro_bodega)
        self.btn_actualizar_bodega.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.btn_actualizar_bodega.setObjectName("btn_actualizar_bodega")
        self.txt_nombre_bodega = QtWidgets.QLineEdit(parent=Registro_bodega)
        self.txt_nombre_bodega.setGeometry(QtCore.QRect(130, 10, 171, 20))
        self.txt_nombre_bodega.setObjectName("txt_nombre_bodega")

        self.retranslateUi(Registro_bodega)
        QtCore.QMetaObject.connectSlotsByName(Registro_bodega)

    def retranslateUi(self, Registro_bodega):
        _translate = QtCore.QCoreApplication.translate
        Registro_bodega.setWindowTitle(_translate("Registro_bodega", "Dialog"))
        self.btn_crear_bodega.setText(_translate("Registro_bodega", "Crear"))
        self.label.setText(_translate("Registro_bodega", "Nombre Bodega"))
        self.label_2.setText(_translate("Registro_bodega", "Cantidad Materiales"))
        self.btn_actualizar_bodega.setText(_translate("Registro_bodega", "Actualizar"))
