# Form implementation generated from reading ui file 'Ui_crear_bodega.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registro_bodega(object):
    def setupUi(self, Registro_bodega):
        Registro_bodega.setObjectName("Registro_bodega")
        Registro_bodega.resize(655, 413)
        self.btn_crear_bodega = QtWidgets.QPushButton(parent=Registro_bodega)
        self.btn_crear_bodega.setGeometry(QtCore.QRect(10, 200, 75, 23))
        self.btn_crear_bodega.setObjectName("btn_crear_bodega")
        self.label = QtWidgets.QLabel(parent=Registro_bodega)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.listView_bodegas = QtWidgets.QListView(parent=Registro_bodega)
        self.listView_bodegas.setGeometry(QtCore.QRect(120, 80, 511, 61))
        self.listView_bodegas.setObjectName("listView_bodegas")
        self.btn_actualizar_bodega = QtWidgets.QPushButton(parent=Registro_bodega)
        self.btn_actualizar_bodega.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.btn_actualizar_bodega.setObjectName("btn_actualizar_bodega")
        self.txt_nombre_bodega = QtWidgets.QLineEdit(parent=Registro_bodega)
        self.txt_nombre_bodega.setGeometry(QtCore.QRect(130, 10, 171, 20))
        self.txt_nombre_bodega.setObjectName("txt_nombre_bodega")
        self.cmb_bodegas_creadas = QtWidgets.QComboBox(parent=Registro_bodega)
        self.cmb_bodegas_creadas.setGeometry(QtCore.QRect(10, 80, 69, 22))
        self.cmb_bodegas_creadas.setObjectName("cmb_bodegas_creadas")
        self.tbl_bodega_creada = QtWidgets.QTableWidget(parent=Registro_bodega)
        self.tbl_bodega_creada.setGeometry(QtCore.QRect(120, 170, 511, 211))
        self.tbl_bodega_creada.setObjectName("tbl_bodega_creada")
        self.tbl_bodega_creada.setColumnCount(5)
        self.tbl_bodega_creada.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_bodega_creada.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_bodega_creada.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_bodega_creada.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_bodega_creada.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_bodega_creada.setHorizontalHeaderItem(4, item)

        self.retranslateUi(Registro_bodega)
        QtCore.QMetaObject.connectSlotsByName(Registro_bodega)

    def retranslateUi(self, Registro_bodega):
        _translate = QtCore.QCoreApplication.translate
        Registro_bodega.setWindowTitle(_translate("Registro_bodega", "Dialog"))
        self.btn_crear_bodega.setText(_translate("Registro_bodega", "Crear"))
        self.label.setText(_translate("Registro_bodega", "Nombre Bodega"))
        self.btn_actualizar_bodega.setText(_translate("Registro_bodega", "Actualizar"))
        item = self.tbl_bodega_creada.horizontalHeaderItem(0)
        item.setText(_translate("Registro_bodega", "Nombre"))
        item = self.tbl_bodega_creada.horizontalHeaderItem(1)
        item.setText(_translate("Registro_bodega", "Codigo"))
        item = self.tbl_bodega_creada.horizontalHeaderItem(2)
        item.setText(_translate("Registro_bodega", "Cantidad"))
        item = self.tbl_bodega_creada.horizontalHeaderItem(3)
        item.setText(_translate("Registro_bodega", "Costo"))
        item = self.tbl_bodega_creada.horizontalHeaderItem(4)
        item.setText(_translate("Registro_bodega", "Fecha"))
