# Form implementation generated from reading ui file 'Ui_Main_Window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main_Window(object):
    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(370, 178)
        self.centralwidget = QtWidgets.QWidget(parent=Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        Main_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(parent=self.menubar)
        self.menuMain.setObjectName("menuMain")
        Main_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main_Window)
        self.statusbar.setObjectName("statusbar")
        Main_Window.setStatusBar(self.statusbar)
        self.actionRegistro_Articulos = QtGui.QAction(parent=Main_Window)
        self.actionRegistro_Articulos.setObjectName("actionRegistro_Articulos")
        self.actionDistribuidores = QtGui.QAction(parent=Main_Window)
        self.actionDistribuidores.setObjectName("actionDistribuidores")
        self.actionBodegas = QtGui.QAction(parent=Main_Window)
        self.actionBodegas.setObjectName("actionBodegas")
        self.actionInventario_Articulos = QtGui.QAction(parent=Main_Window)
        self.actionInventario_Articulos.setObjectName("actionInventario_Articulos")
        self.menuMain.addAction(self.actionRegistro_Articulos)
        self.menuMain.addAction(self.actionDistribuidores)
        self.menuMain.addAction(self.actionBodegas)
        self.menuMain.addAction(self.actionInventario_Articulos)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "MainWindow"))
        self.menuMain.setTitle(_translate("Main_Window", "Menu"))
        self.actionRegistro_Articulos.setText(_translate("Main_Window", "Registro Articulos"))
        self.actionDistribuidores.setText(_translate("Main_Window", "Distribuidores"))
        self.actionBodegas.setText(_translate("Main_Window", "Bodegas"))
        self.actionInventario_Articulos.setText(_translate("Main_Window", "Inventario Articulos"))
