# Form implementation generated from reading ui file 'Ui_registro_distribuidor.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventana_distribuidor(object):
    def setupUi(self, ventana_distribuidor):
        ventana_distribuidor.setObjectName("ventana_distribuidor")
        ventana_distribuidor.resize(400, 300)
        self.btn_crear_distribuidor = QtWidgets.QPushButton(parent=ventana_distribuidor)
        self.btn_crear_distribuidor.setGeometry(QtCore.QRect(10, 190, 75, 23))
        self.btn_crear_distribuidor.setObjectName("btn_crear_distribuidor")
        self.label = QtWidgets.QLabel(parent=ventana_distribuidor)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=ventana_distribuidor)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=ventana_distribuidor)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_3.setObjectName("label_3")
        self.txt_nombre_dist = QtWidgets.QLineEdit(parent=ventana_distribuidor)
        self.txt_nombre_dist.setGeometry(QtCore.QRect(130, 10, 113, 20))
        self.txt_nombre_dist.setObjectName("txt_nombre_dist")
        self.txt_ced_juridica_dist = QtWidgets.QLineEdit(parent=ventana_distribuidor)
        self.txt_ced_juridica_dist.setGeometry(QtCore.QRect(130, 40, 113, 20))
        self.txt_ced_juridica_dist.setObjectName("txt_ced_juridica_dist")
        self.txt_telefono_dist = QtWidgets.QLineEdit(parent=ventana_distribuidor)
        self.txt_telefono_dist.setGeometry(QtCore.QRect(130, 70, 113, 20))
        self.txt_telefono_dist.setObjectName("txt_telefono_dist")
        self.cmb_distribuidores = QtWidgets.QComboBox(parent=ventana_distribuidor)
        self.cmb_distribuidores.setGeometry(QtCore.QRect(10, 110, 69, 22))
        self.cmb_distribuidores.setObjectName("cmb_distribuidores")

        self.retranslateUi(ventana_distribuidor)
        QtCore.QMetaObject.connectSlotsByName(ventana_distribuidor)

    def retranslateUi(self, ventana_distribuidor):
        _translate = QtCore.QCoreApplication.translate
        ventana_distribuidor.setWindowTitle(_translate("ventana_distribuidor", "Dialog"))
        self.btn_crear_distribuidor.setText(_translate("ventana_distribuidor", "Crear"))
        self.label.setText(_translate("ventana_distribuidor", "Nombre Distribuidor"))
        self.label_2.setText(_translate("ventana_distribuidor", "Ced-Juridica."))
        self.label_3.setText(_translate("ventana_distribuidor", "Telefono."))
