# Form implementation generated from reading ui file 'Ui_registro.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registro_Ui(object):
    def setupUi(self, Registro_Ui):
        Registro_Ui.setObjectName("Registro_Ui")
        Registro_Ui.resize(597, 421)
        self.btn_registrar_articulo = QtWidgets.QPushButton(parent=Registro_Ui)
        self.btn_registrar_articulo.setGeometry(QtCore.QRect(430, 160, 75, 23))
        self.btn_registrar_articulo.setObjectName("btn_registrar_articulo")
        self.label = QtWidgets.QLabel(parent=Registro_Ui)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Registro_Ui)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Registro_Ui)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Registro_Ui)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 101, 16))
        self.label_4.setObjectName("label_4")
        self.txt_nombre_articulo = QtWidgets.QLineEdit(parent=Registro_Ui)
        self.txt_nombre_articulo.setGeometry(QtCore.QRect(130, 10, 191, 20))
        self.txt_nombre_articulo.setClearButtonEnabled(False)
        self.txt_nombre_articulo.setObjectName("txt_nombre_articulo")
        self.txt_codigo_articulo = QtWidgets.QLineEdit(parent=Registro_Ui)
        self.txt_codigo_articulo.setGeometry(QtCore.QRect(130, 40, 191, 20))
        self.txt_codigo_articulo.setObjectName("txt_codigo_articulo")
        self.txt_cantidad_articulo = QtWidgets.QLineEdit(parent=Registro_Ui)
        self.txt_cantidad_articulo.setGeometry(QtCore.QRect(130, 70, 191, 20))
        self.txt_cantidad_articulo.setObjectName("txt_cantidad_articulo")
        self.txt_costo_articulo = QtWidgets.QLineEdit(parent=Registro_Ui)
        self.txt_costo_articulo.setGeometry(QtCore.QRect(130, 100, 191, 20))
        self.txt_costo_articulo.setObjectName("txt_costo_articulo")
        self.label_5 = QtWidgets.QLabel(parent=Registro_Ui)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 101, 16))
        self.label_5.setObjectName("label_5")
        self.cbx_bodega_N = QtWidgets.QComboBox(parent=Registro_Ui)
        self.cbx_bodega_N.setGeometry(QtCore.QRect(130, 130, 121, 22))
        self.cbx_bodega_N.setObjectName("cbx_bodega_N")
        self.date_fecha_articulo = QtWidgets.QDateEdit(parent=Registro_Ui)
        self.date_fecha_articulo.setGeometry(QtCore.QRect(130, 160, 121, 22))
        self.date_fecha_articulo.setObjectName("date_fecha_articulo")
        self.label_6 = QtWidgets.QLabel(parent=Registro_Ui)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_6.setObjectName("label_6")
        self.list_bodega_Madera = QtWidgets.QListView(parent=Registro_Ui)
        self.list_bodega_Madera.setGeometry(QtCore.QRect(10, 220, 571, 192))
        self.list_bodega_Madera.setObjectName("list_bodega_Madera")
        self.cbox_bodega2 = QtWidgets.QCheckBox(parent=Registro_Ui)
        self.cbox_bodega2.setGeometry(QtCore.QRect(340, 130, 70, 17))
        self.cbox_bodega2.setObjectName("cbox_bodega2")
        self.cbx_bodega1 = QtWidgets.QCheckBox(parent=Registro_Ui)
        self.cbx_bodega1.setGeometry(QtCore.QRect(260, 130, 70, 17))
        self.cbx_bodega1.setObjectName("cbx_bodega1")

        self.retranslateUi(Registro_Ui)
        QtCore.QMetaObject.connectSlotsByName(Registro_Ui)

    def retranslateUi(self, Registro_Ui):
        _translate = QtCore.QCoreApplication.translate
        Registro_Ui.setWindowTitle(_translate("Registro_Ui", "Dialog"))
        self.btn_registrar_articulo.setText(_translate("Registro_Ui", "Registrar"))
        self.label.setText(_translate("Registro_Ui", "Nombre Articulo"))
        self.label_2.setText(_translate("Registro_Ui", "Codigo Articulo"))
        self.label_3.setText(_translate("Registro_Ui", "Cantidad Articulo"))
        self.label_4.setText(_translate("Registro_Ui", "Costo Articulo"))
        self.label_5.setText(_translate("Registro_Ui", "Asignar Bodega"))
        self.label_6.setText(_translate("Registro_Ui", "Fecha"))
        self.cbox_bodega2.setText(_translate("Registro_Ui", "Bodega 2"))
        self.cbx_bodega1.setText(_translate("Registro_Ui", "Bodega 1"))
